user  www-data;
worker_processes  auto;

load_module modules/ngx_http_trim_cert_module.so;
#error_log  logs/error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;

pid        /run/nginx.pid;


events {
    worker_connections  10240;
}


http {
    #
    map $http_upgrade $connection_upgrade {
                default upgrade;
                ''      close;
    }
    
    #
    upstream trim_cgi {
        server unix:/run/trim_cgi.socket;
    }

    upstream trim_upload {
        server unix:/run/trim_upload_srv.socket;
    }

    include       mime.types;
    default_type  application/octet-stream;

    #log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
    #                  '$status $body_bytes_sent "$http_referer" '
    #                  '"$http_user_agent" "$http_x_forwarded_for"';

    #access_log  logs/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    #keepalive_timeout  0;
    keepalive_timeout  65;

    #gzip  on;
   
    # nginx上传文件最大限制
    client_max_body_size 1000000g;
    trim_cert_cfg_path /usr/trim/etc/network_gateway_cert.conf;
    server_tokens off;

    server {
	listen 0.0.0.0:5666 default_server;
	listen [::]:5666 ipv6only=on default_server;
	listen 0.0.0.0:5667 ssl default_server;
	listen [::]:5667 ssl ipv6only=on default_server;
	listen 0.0.0.0:8000 default_server;
	listen [::]:8000 ipv6only=on default_server;
	listen 0.0.0.0:8001 ssl default_server;
	listen [::]:8001 ssl ipv6only=on default_server;
	listen 0.0.0.0:80 default_server;
	listen [::]:80 ipv6only=on default_server;
	listen 0.0.0.0:443 ssl default_server;
	listen [::]:443 ssl ipv6only=on default_server;
	if ($server_port = 80) {
		return 302 $scheme://$host:5666$request_uri;
	}
	if ($server_port = 443) {
		return 302 $scheme://$host:5667$request_uri;
	}
	set $Cache_Control_val "";
	set $Pragma_val "";
	set $Expires_val "";
	if ($request_uri ~ "\.html$") {
		set $Cache_Control_val "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
		set $Pragma_val "no-cache";
		set $Expires_val "0";
	}
	add_header Cache-Control $Cache_Control_val;
	add_header Pragma $Pragma_val;
	add_header Expires $Expires_val;

        #server_name  _;



        trim_hook_cert_switch  on;
        ssl_certificate      $ssl_server_name;
        ssl_certificate_key  $ssl_server_name;

        ssl_session_cache    shared:SSL:1m;
        ssl_session_timeout  5m;

        ssl_ciphers  HIGH:!aNULL:!MD5;
        ssl_prefer_server_ciphers  on;

        root /usr/trim/www;

        index index.html index.htm;

        error_page 404 /index.html;

        # websocket配置
        location /websocket {
                proxy_pass http://trim_cgi;
                proxy_http_version 1.1;
                proxy_set_header X-Real-IP      $remote_addr;
                proxy_set_header Upgrade        $http_upgrade;
                proxy_set_header Connection     "upgrade";
        }

        # upload配置
        location /upload {
                proxy_pass http://trim_upload;
                keepalive_timeout  0;
                proxy_http_version 1.1;
                proxy_set_header X-Real-IP      $remote_addr;
                proxy_request_buffering off;
                client_body_buffer_size 512K;
                tcp_nopush on;
        }

        location /download {
                alias  /;
             
                download_auth on;
        }
        


        location /appui {
                alias  /vol0/@appui;
        }

        include conf.d/*.conf;
    }
}
